#!/usr/bin/env python3
import argparse
import csv
from datetime import datetime
from pathlib import Path
from typing import Iterable


def batched(rows: Iterable[dict], size: int) -> Iterable[list[dict]]:
    batch: list[dict] = []
    for row in rows:
        batch.append(row)
        if len(batch) >= size:
            yield batch
            batch = []
    if batch:
        yield batch


def parse_csv(path: Path) -> Iterable[dict]:
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            yield {
                "call_id": row["call_id"],
                "call_time": datetime.strptime(row["call_time"], "%Y-%m-%d %H:%M:%S"),
                "client_id": row["client_id"],
                "region_code": row["region_code"],
                "campaign_type": row["campaign_type"],
                "call_status": row["call_status"],
                "client_response": row["client_response"],
                "duration_sec": int(row["duration_sec"]),
                "follow_up_required": row["follow_up_required"].lower() == "true",
            }


def main() -> None:
    parser = argparse.ArgumentParser(description="Load transactions_v2 CSV to YDB with Python SDK.")
    parser.add_argument("--endpoint", required=True, help="Example: grpcs://ydb.serverless.yandexcloud.net:2135")
    parser.add_argument("--database", required=True, help="Example: /ru-central1/<cloud>/<database>")
    parser.add_argument("--table-path", required=True, help="Full table path, for example <database>/transactions_v2")
    parser.add_argument("--input", required=True, help="CSV path generated by generate_transactions_v2.py")
    parser.add_argument("--sa-key-file", default=None, help="Optional service account key JSON.")
    parser.add_argument("--batch-size", type=int, default=1000)
    args = parser.parse_args()

    try:
        import ydb
        import ydb.iam
    except ImportError as exc:
        raise SystemExit("Install dependency first: pip install ydb") from exc

    if args.sa_key_file:
        credentials = ydb.iam.ServiceAccountCredentials.from_file(args.sa_key_file)
    else:
        credentials = ydb.iam.MetadataUrlCredentials()

    driver_config = ydb.DriverConfig(
        endpoint=args.endpoint,
        database=args.database,
        credentials=credentials,
    )
    driver = ydb.Driver(driver_config)
    driver.wait(fail_fast=True, timeout=30)
    pool = ydb.SessionPool(driver)

    column_types = ydb.BulkUpsertColumns()
    column_types.add_column("call_id", ydb.OptionalType(ydb.PrimitiveType.Utf8))
    column_types.add_column("call_time", ydb.OptionalType(ydb.PrimitiveType.Timestamp))
    column_types.add_column("client_id", ydb.OptionalType(ydb.PrimitiveType.Utf8))
    column_types.add_column("region_code", ydb.OptionalType(ydb.PrimitiveType.Utf8))
    column_types.add_column("campaign_type", ydb.OptionalType(ydb.PrimitiveType.Utf8))
    column_types.add_column("call_status", ydb.OptionalType(ydb.PrimitiveType.Utf8))
    column_types.add_column("client_response", ydb.OptionalType(ydb.PrimitiveType.Utf8))
    column_types.add_column("duration_sec", ydb.OptionalType(ydb.PrimitiveType.Uint32))
    column_types.add_column("follow_up_required", ydb.OptionalType(ydb.PrimitiveType.Bool))

    total = 0
    for batch in batched(parse_csv(Path(args.input)), args.batch_size):
        pool.retry_operation_sync(
            lambda session, b=batch: session.bulk_upsert(args.table_path, b, column_types)
        )
        total += len(batch)
        print(f"Loaded {total} rows")

    driver.stop()
    print(f"Done. Loaded {total} rows to {args.table_path}")


if __name__ == "__main__":
    main()

